name = "SashaVova_1201"
author = "Sasha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d0c5fa54796e938fa59b238f137c8bd4db82d2b3c69fa3aaf9e0324fc65c342"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
