name = "SashaVova_1201"
author = "Sasha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbbbeb714bddb48e3639fba2be128bf8b9307d41c8c39f176559c4d9ab93fdfa"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
