name = "SashaVova_1201"
author = "Sasha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7440f134b9df004b462c5dbb59a11385973a9b0f1bbf27dd54cfe58529aa818c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
