#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 12 04:17:26 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=BSL_v10.1.3.zip
